- hosts: control
  become: true
  tasks:
          - name: Installing tools
            apt: name={{item}} state=present update_cache=yes
            with_items:
                    - curl
                    - python3-httplib2
