---
- name: Installing mysql database
  become: true
  hosts: databaseservers
  tasks:
          - name: Installing msql
            apt: name=mysql-server state=present update_cache=yes     

          - name: Ensure mysql is started
            service: name=mysql state=started enabled=yes
