---
- name: Installing mysql database
  become: true
  hosts: databaseservers
  tasks:
          - name: Install database tools
            apt: name={{item}} state=present
            with_items:
                    - python3-mysqldb

          - name: Installing msql
            apt: name=mysql-server state=present update_cache=yes     

          - name: Ensure mysql is started
            service: name=mysql state=started enabled=yes

          - name: Ensure mysql is listening on all ports
            lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf  regex=^bind-address line="bind-address=0.0.0.0"
            notify: Restart mysql

          - name: Create demo database
            mysql_db: name=demo state=present

          - name: create demo user
            mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present

  handlers:
          - name: Restart mysql
            service: name=mysql state=restarted
