---
# Bring stack down
- hosts: loadbalancer
  become: true
  tasks:
          - name: Stopping nginx loadbalancer
            service: name=nginx state=stopped 


- hosts: webservers
  become: true
  tasks:
          - name: Stopping apache2 webserver
            service: name=apache2 state=stopped

- hosts: databaseservers
  become: true
  tasks:
          - name: Restarting mysql
            service: name=mysql state=restarted


# Bringing stack back up
- hosts: webservers
  become: true
  tasks:
          - name: Restarting apache2 webserver
            service: name=apache2 state=started

- hosts: loadbalancer
  become: true
  tasks:
          - name: Restarting nginx loadbalancer
            service: name=nginx state=started


